### ISSUE TITLE
Possible issues with Semeru Runtime tar archives for MacOs

### ISSUE THREAD

**Issue by jbartok** [ibmruntimes/Semeru-Runtimes#15] opened 2022-01-07 07:37 UTC
There seems to be some kind of issue with, or at least something weird in the headers of the `ibm-semeru-open-jdk_x64_mac_xxx.tar.gz` files you can download from IBM (or get via Adoptium).

We at Gradle have had problems decompressing these archives because we are using Apache Ant code, which is definitely not the most robust (other decompression tools can manage the archives just fine). Even though these problems have been definitely caused by Apache Ant code, the nature of the bug also suggests that the archives themselves are not quite right either. 

To be more specific, the exact Apache Ant code which breaks the decompression is this line: https://github.com/apache/ant/blob/711132a7dd66b2e18c09c9dcae2aba94b0ff798c/src/main/org/apache/tools/tar/TarEntry.java#L1019

Apparently, it draws some wrong conclusions based on the archive header and then misbehaves, i.e. appends some garbage prefix to file names. But since it has been working for years without manifesting this issue (both Ant and Gradle do have significant usage), I suspect that the archives might have something not quite right in their headers.

One thing that looks suspicious to me is that in these archives the file names seem to start with a `/./` type of element, as opposed to simply the top-level directory names as in other archives I've tested. Maybe it's related. 

If somebody could take a look, we would highly appreciate it. If you need me to try to come up with some simplified reproducer or something, pls. let me know.

**Comment by AdamBrousseau** [comment] 2022-01-20 06:23
I think this is what you're referring to in your suspicion
![image](https://user-images.githubusercontent.com/6430052/150283478-0fda0498-f15e-4eac-85e8-00c93852a53f.png)
Seems to be specific to Mac. Looking back at older releases, Adopt had this issue as well on both OpenJ9 and Hotspot but it seems to have resolved upon the first release out of Adoptium. Not sure why yet or why it still affects us (we mirror the Adopt build scripts).
@jbartok would you be able to confirm that this [build](https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jre_x64_mac_hotspot_11.0.11_9.tar.gz) fails and this [build](https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.12%2B7/OpenJDK11U-jre_x64_mac_hotspot_11.0.12_7.tar.gz) passes? If this is the case, I think that will confirm your theory. in the meantime I'll dig into the archive creation to see if I can find the problem.

**Comment by jbartok** [comment] 2022-01-20 07:24
@AdamBrousseau I've run tests with the two archives you provided. I can clearly see the difference between them (the good one contains tar entries named properly, like directory `jdk-11.0.12+7-jre`, while the bad one has the dot prefix, like `./._jdk-11.0.11+9-jre`). But, both can be uncompressed without problems, not like the Semeru archives I'm initially complained about.

Seems like not the current directory dot in the entry names is the fundamental problem, but something in the archive header. When uncompressing with Ant, for the Semeru archives I'm seeing wildly messed up entry names, like this:

![image](https://user-images.githubusercontent.com/6204813/150292098-4fec7bb2-698c-44cf-8617-a8f56ff79a51.png)

**Comment by AdamBrousseau** [comment] 2022-02-08 15:55
I'm wondering if the signing & notarization process on our end is causing the issue. I have sent József a link to an unsigned tarball for testing.

**Comment by jbartok** [comment] 2022-02-09 08:09
FYI: trivial reproducer to showcase the Ant failure added here: https://github.com/jbartok/semeru-issue-15-reproducer

**Comment by jbartok** [comment] 2022-03-03 08:28
@narkedi How we extract these archives is something we will take care of, no worries. But don't you think the archives themselves would maybe need some kind of fixing/improvement of their own?

**Comment by narkedi** [comment] 2022-03-03 10:04
Exactly @jbartok, agree that the archive should be fixed. I just wanted to share the work around incase it was not tried already. We will expedite options and see that the issue is resolved. Thanks !!

**Comment by jbartok** [comment] 2022-04-13 08:09
Hi. Any progress on this? Rgds

**Comment by narkedi** [comment] 2022-07-19 12:46
@amankr55 We were actually not able to reproduce the same issue, we did raise this issue with the concerned but there is no solution yet as of now. Apologies that there is no break through yet. Will try to see how this can be achieved. Will try to reproduce the issue with the latest binary and see that its a strong case to get it fixed.

**Comment by keithc-ca** [comment] 2022-10-25 17:54
It seems GNU tar will consider the archive to be in `STAR_FORMAT`, see [list.c](https://git.savannah.gnu.org/cgit/tar.git/tree/src/list.c#n632). It also considers the prefix to be empty if it starts with a `NUL`, while ant considers the prefix to consist of everything up to the last non-`NUL` character. The macOS tool is producing entries like this, with non-zero content in the last 24 bytes of a header.
```
$ hexdump -Cv archive.tar | head -32
00000000  2e 2f 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |./..............|
00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000040  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000050  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000060  00 00 00 00 30 30 30 37  30 30 20 00 30 30 30 37  |....000700 .0007|
00000070  36 35 20 00 30 30 30 31  32 30 20 00 30 30 30 30  |65 .000120 .0000|
00000080  30 30 30 30 30 30 20 00  31 34 32 37 37 37 31 37  |000000 .14277717|
00000090  34 31 31 00 30 31 33 37  32 30 20 00 35 00 00 00  |411.013720 .5...|
000000a0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000000b0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000000c0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000000d0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000000e0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000000f0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000100  00 75 73 74 61 72 00 30  30 61 70 70 73 65 72 76  |.ustar.00appserv|
00000110  69 63 65 73 00 00 00 00  00 00 00 00 00 00 00 00  |ices............|
00000120  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000130  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000140  00 00 00 00 00 00 00 00  00 30 30 30 30 30 30 20  |.........000000 |
00000150  00 30 30 30 30 30 30 20  00 00 00 00 00 00 00 00  |.000000 ........|
00000160  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000170  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000180  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000190  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000001a0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000001b0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000001c0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000001d0  00 00 00 00 00 00 00 00  00 00 00 00 31 34 32 37  |............1427|
000001e0  37 37 31 37 34 32 30 00  31 34 32 37 37 37 31 37  |7717420.14277717|
000001f0  34 31 31 00 00 00 00 00  00 00 00 00 00 00 00 00  |411.............|
```
I'm inclined to think we have two problems: the macOS implementation of tar and the problem in ant that includes `NUL` characters in the file prefix.

**Comment by keithc-ca** [comment] 2022-10-26 17:58
I think the right place to fix this is in `TarEntry`:
```
diff --git a/src/main/org/apache/tools/tar/TarUtils.java b/src/main/org/apache/tools/tar/TarUtils.java
index b6e12c4..f6f1036 100644
--- a/src/main/org/apache/tools/tar/TarUtils.java
+++ b/src/main/org/apache/tools/tar/TarUtils.java
@@ -286,9 +286,9 @@
                                    final ZipEncoding encoding)
         throws IOException {
 
-        int len = length;
-        for (; len > 0; len--) {
-            if (buffer[offset + len - 1] != 0) {
+        int len = 0;
+        for (; len < length; ++len) {
+            if (buffer[offset + len] == 0) {
                 break;
             }
         }
```
I created https://github.com/apache/ant/pull/194.

**Comment by keithc-ca** [comment] 2022-11-07 17:41
The fix is now merged. I assume it will be included in the next release of ant.

**Closed by keithc-ca** 2022-11-07 17:41 UTC
